### ISSUE TITLE
请教一个问题: 为什么不是num_node * num_node? 为什么+1?

### ISSUE THREAD

**Issue by ysgncss** [LindgeW/TextLevelGNN#1]
self.edge_weight = nn.Embedding((num_node-1)*(num_node-1)+1, 1, padding_idx=0)   # edge weight

**Comment by LindgeW** [comment]
+1 for zero padding

**Comment by LindgeW** [comment]
+1 for padding

**Comment by LindgeW** [comment]
num_node是实际的word数量, 如果词表中包含了pad，用(num_node-1) * (num_node-1), +1是留给zero padding
当然num_node * num_node也不会错, 只是embedding表更大了

**Comment by LindgeW** [comment]
num_node是实际的word数量，如果词表中包含了pad，用(num_node-1) * (num_node-1), +1是单独留给zero padding

**Comment by LindgeW** [comment]
我这里的num_node是根据词表大小取的，并且包含了pad

**Comment by ysgncss** [comment]
不好意思，还想请教一个问题， 对于一个句中出现的多个单词，是怎么处理的呢？ 比如 "where are you？Are you OK?" , are 出现2次，you 也出现了2次， 预处理时句子会变成什么？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lam chi"<notifications@github.com&gt;; 
发送时间: 2020年9月11日(星期五) 晚上7:12
收件人: "LindgeW/TextLevelGNN"<TextLevelGNN@noreply.github.com&gt;; 
抄送: "終究，莪呮媞①嗰蓜捔"<2207589533@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [LindgeW/TextLevelGNN] 请教一个问题: 为什么不是num_node * num_node? 为什么+1? (#1)





 
我这里的num_node是根据词表大小取的，并且包含了pad

**Comment by LindgeW** [comment]
并无特殊处理，are或you出现多次意味着它们的邻居节点更多了，对于与每个邻居节点的连边权重是不同的
