### ISSUE TITLE
是有向图嘛？

### ISSUE THREAD

**Issue by 1eclipse** [LindgeW/TextLevelGNN#2]
您好，我看到您论文的图1，构造的有向图，实际还是按照无向图处理的对吗？

**Comment by LindgeW** [comment]
其实还是有向图，因为节点间的两条边的权重不同

**Comment by 1eclipse** [comment]
嗯，请问您是如何确定边权重呢？为什么要做有向图这样的操作呢，后面消息传递机制似乎是无向图的传递方式？感谢您回答

**Comment by LindgeW** [comment]
首先构图方式是根据一句话中，词的邻接关系来的，由当前词指向其上下文窗口内的领近词（体现出方向性），并且每个词赋予的权重不同（**每条边的索引不同**，对应的LookupTable embedding不同）,换句话讲，当轮到出现窗口内的词指向当前词时，因为边索引是不同的，对应的权重 (embedding)也就不同。可以理解为这两个词彼此对对方的影响程度是不同的（无向图体现不出这种差异性）。至于节点更新的MPM和无向图是类似的。

**Comment by 1eclipse** [comment]
嗯嗯，我理解为什么要用有向图了。就是您是怎么确定连边权重的呢，采用的什么方法，似乎论文里面没有具体说用的什么方法。我看其他论文大多用的PMI，但是PMI确定的权重P(x,y)=P(y,x)，是不能体现两个词之间权重差异性，所以想知道您的文章用的什么方法确定权重的呢。

**Comment by LindgeW** [comment]
PMI一般是需要对整个语料库进行统计计算，本文每次处理的是单个文本（动态构图），连边策略是基于当前词的局部上下文，至于边的权重是先随机初始化，然后在消息传递过程中不断更新学习的。

**Comment by 1eclipse** [comment]
嗯嗯，我知道了，谢谢您

**Comment by 1eclipse** [comment]
您好，抱歉又要打扰了，还是之前边权重的问题，您上次说边权重是随机初始化，但是论文中边权重取自全局共享矩阵，既然是共享矩阵那怎么是随机初始化呢？

**Comment by LindgeW** [comment]
这个不矛盾啊，全局共享矩阵是指所有两个词(节点)间的边共用同一个|V|*|V|的矩阵（对于整个数据集来说是不变的），至于矩阵元素（即边的权重）是随机初始化的

**Comment by 1eclipse** [comment]
那后续更新权重的时候，也同时更新全局共享矩阵吗？如果是这样的话，因为是单个文本一个图，两个节点之间的权重在不同图里更新后的结果不一样，那怎么更新全局共享矩阵呢？

**Comment by LindgeW** [comment]
文本图中对应于共享矩阵内的边的权重会更新 (局部)

**Comment by LindgeW** [comment]
因为是权重矩阵共享，相同的两个词(节点)在不同文本(图)中，对于不同的上下文，更新过程保证能学到全局上下文信息（尽管是局部构图和更新）

**Comment by 1eclipse** [comment]
我不太理解怎么学习全局信息。更新过程不是只考虑相邻节点信息吗？

**Comment by LindgeW** [comment]
更新是每次只更新文本图中的邻接节点边的权重，但是权重矩阵是共享的啊，就好比w1和w2这两个有领接关系的词可能出现在整个语料的不同文本图中，但是对应于权重矩阵中是一样的，意味着w1和w2之间的边权重学到的是二者在不同的上下文中的信息。
（建议再仔细阅读一下论文）

**Comment by 1eclipse** [comment]
嗯，好，十分感谢您！

**Comment by LindgeW** [comment]
不客气
