### ISSUE TITLE
内存消耗

### ISSUE THREAD

**Issue by 1eclipse** [LindgeW/TextLevelGNN#3]
您好，关于内存消耗的计算我不是很清楚要怎么计算，我用的是CPU。请问一下要怎么计算内存消耗呢？之前没有做过内存消耗的计算经验，希望您能解答一下，或者有没有相关资料我能参考一下呢？谢谢谢！

**Comment by LindgeW** [comment]
CPU不擅长大矩阵运算，建议用GPU跑，速度相当快

**Comment by LindgeW** [comment]
内存一般不会自己计算，这个运行过程是不确定的，一般会计算模型参数量(规模)

**Comment by 1eclipse** [comment]
您论文中的内存消耗是如何计算出来的呢？

**Comment by LindgeW** [comment]
内存占用包括模型权重参数本身占用以及各中间变量(梯度)占用，运行时一般会有额外开销，实际占用往往高于理论计算结果
https://github.com/Oldpan/Pytorch-Memory-Utils

**Comment by 1eclipse** [comment]
好的谢谢
