### ISSUE TITLE
关于内存消耗的一个疑问

### ISSUE THREAD

**Issue by xhjcxxl** [LindgeW/TextLevelGNN#5]
GPU Memory Track | 19-Oct-20-16:54:14 | Total Used Memory:651.4  Mb

At __main__ train: line 123                          Total Used Memory:651.4  Mb

At __main__ train: line 127                          Total Used Memory:651.4  Mb

+ | 1 * Size:(52, 200)            | Memory: 0.0416 M | <class 'torch.nn.parameter.Parameter'>
+ | 1 * Size:(52,)                | Memory: 0.0002 M | <class 'torch.nn.parameter.Parameter'>
+ | 1 * Size:(32,)                | Memory: 0.0001 M | <class 'torch.Tensor'>
+ | 1 * Size:(2107922, 1)         | Memory: 8.4316 M | <class 'torch.nn.parameter.Parameter'>
+ | 1 * Size:(5364, 200)          | Memory: 4.2912 M | <class 'torch.nn.parameter.Parameter'>

At __main__ train: line 152                          Total Used Memory:1045.3 Mb

+ | 1 * Size:(32, 52)             | Memory: 0.0066 M | <class 'torch.Tensor'>

At __main__ train: line 154                          Total Used Memory:1133.4 Mb

+ | 3 * Size:(52,)                | Memory: 0.0006 M | <class 'torch.nn.parameter.Parameter'>
+ | 3 * Size:(52, 200)            | Memory: 0.1248 M | <class 'torch.Tensor'>
+ | 3 * Size:(5364, 200)          | Memory: 12.873 M | <class 'torch.nn.parameter.Parameter'>
+ | 3 * Size:(5364, 200)          | Memory: 12.873 M | <class 'torch.Tensor'>
+ | 3 * Size:(52, 200)            | Memory: 0.1248 M | <class 'torch.nn.parameter.Parameter'>
+ | 3 * Size:(52,)                | Memory: 0.0006 M | <class 'torch.Tensor'>
+ | 3 * Size:(2107922, 1)         | Memory: 25.295 M | <class 'torch.Tensor'>
+ | 3 * Size:(2107922, 1)         | Memory: 25.295 M | <class 'torch.nn.parameter.Parameter'>
+ | 3 * Size:()                   | Memory: 1.2e-0 M | <class 'torch.Tensor'>
+ | 2 * Size:(32,)                | Memory: 0.0002 M | <class 'torch.Tensor'>
- | 1 * Size:(52, 200)            | Memory: 0.0416 M | <class 'torch.nn.parameter.Parameter'> 
- | 1 * Size:(32,)                | Memory: 0.0001 M | <class 'torch.Tensor'> 
- | 1 * Size:(52,)                | Memory: 0.0002 M | <class 'torch.nn.parameter.Parameter'> 
- | 1 * Size:(2107922, 1)         | Memory: 8.4316 M | <class 'torch.nn.parameter.Parameter'> 
- | 1 * Size:(5364, 200)          | Memory: 4.2912 M | <class 'torch.nn.parameter.Parameter'> 

At __main__ train: line 170                          Total Used Memory:1213.1 Mb

At __main__ train: line 152                          Total Used Memory:1213.1 Mb

At __main__ train: line 154                          Total Used Memory:1213.1 Mb

At __main__ train: line 170                          Total Used Memory:1234.1 Mb

At __main__ train: line 152                          Total Used Memory:1234.1 Mb

At __main__ train: line 154                          Total Used Memory:1234.1 Mb

At __main__ train: line 170                          Total Used Memory:1234.1 Mb

麻烦你看一下，能说一下内存消耗是怎么计算出来的，这是我通过GPU跑的R52的结果

**Comment by LindgeW** [comment]
At main train: line xxx Total Used Memory:  表示执行到当前代码行时占用的总显存，从123行执行到170行，占用的显存大约为1234.1 - 651.4 = 582.7Mb

**Comment by xhjcxxl** [comment]
这样算下来，与论文里951M，内存消耗不符合呀？这个差太多了，对了，我只跑了几个epoch，没有跑到200个

**Comment by LindgeW** [comment]
这只是对原文的大致复现

**Comment by xhjcxxl** [comment]
明白了，谢谢
