### ISSUE TITLE
准确率问题

### ISSUE THREAD

**Issue by qirmcmww** [LindgeW/TextLevelGNN#6]
复现模型的准确率和作者在论文中给出的准确率差距非常大，请问您的代码有什么改进空间吗？

**Comment by LindgeW** [comment]
有的，比如对边的优化，想想如何更有效地赋予边的权重

**Comment by qirmcmww** [comment]
尝试使用激活函数将权重控制在[-1,1]之间，发现模型很快梯度消失。

**Comment by LindgeW** [comment]
为什么要限制权重范围？

**Comment by qirmcmww** [comment]
r‘ = (1-n)M+nR 作者说n是依靠网络训练的，想着如果不限制范围的话，会可能训练出不符合常理的数，就尝试着限制了一下

**Comment by qirmcmww** [comment]
还尝试了使用GRU来组合更新前和更新后的信息，也会很快梯度消失

**Comment by LindgeW** [comment]
n是有可能训练出不合理的值，之前试了用softmax约束，但是效果不明显；

**Comment by qirmcmww** [comment]
感觉可改进的空间不太大了

**Comment by ysgncss** [comment]
应用在中文数据集上有啥注意的吗？效果似乎不好，基线都跑不过呀。。。
