### ISSUE TITLE
关于局部节点之间边index的计算公式的问题？

### ISSUE THREAD

**Issue by Henry199898** [LindgeW/TextLevelGNN#7]
您好，有个问题想要请教
https://github.com/LindgeW/TextLevelGNN/blob/e63c80a4be553c3f55c4810d736c46d7b98e7369/utils/datautil.py#L50
这一行公式是怎么得出的呢？如何代表局部图中两个节点之间的边？
谢谢您！

**Comment by LindgeW** [comment]
这相当于邻接词在|V|*|V|矩阵按行存储的索引，nx只是邻近词的词表索引，反映不出和中心词存在边的关系，所以需要转换成在矩阵中的索引

**Comment by Henry199898** [comment]
好的，感谢您！
