### ISSUE TITLE
我的数据集很大，GPU会显存溢出，代码有优化空间吗

### ISSUE THREAD

**Issue by ysgncss** [LindgeW/TextLevelGNN#8]

**Comment by LindgeW** [comment]
batch小点，然后采用gradient accumulation.

**Comment by ysgncss** [comment]
不行  24G都不行，裂开了

**Comment by LindgeW** [comment]
我估计是在这里
`self.node_embedding = nn.Embedding.from_pretrained(torch.from_numpy(pre_embed), freeze=False)`
出问题了

**Comment by LindgeW** [comment]
可能是在node embedding炸的，预训练词向量规模太大，整个加载到内存中微调不太行

**Comment by ysgncss** [comment]
应用在中文数据集上有啥注意的吗？效果似乎不好

**Comment by Al-Dailami** [comment]
Hello, I also meet the same problem. Is there any solution for this problem (OOM)?!

**Comment by shaoyangxu** [comment]
感觉GCN用cpu训练就够够的啊
